### ISSUE TITLE
Pop-up text cannot be replaced

### ISSUE THREAD

**Issue by liraqb** [jingzhiMo/text-block#3]
Example: [Features - CodiMD](https://demo.codimd.org/features)

At the end of the page:

> This is an HTML abbreviation example.

The pop-up text of "HTML" cannot be replaced.

**Comment by jingzhiMo** [comment]
`pop-up text` is a attributie(`title`) of element, not element text content. Now `text-block` is not replaced on `title attribute`. That is a new feature.
